### ISSUE TITLE
Several reference in rougescore

### ISSUE THREAD

**Issue by MahdiDoost** [bdusell/rougescore#1]
In the Name of God.
hello

I write followed code for usinge rougescore:
`import rougescore

summary = "I am a teacher."
reference = "I 'm a teacher."

result = rougescore.rouge_1(summary, reference,0)

print(result)`

How can I have four reference?
thank you

**Comment by bdusell** [comment]
Hi,

This should be better documented, but all of the rouge functions take _lists_ of summaries and references as arguments. The sentences must also be tokenized beforehand; otherwise you are computing character-level accuracy.

```
summaries = [summary.split()]
references = [reference1.split(), reference2.split(), ...]
result = rougescore.rouge_1(summaries, references, 0)
```

Hope this helps.

**Comment by MahdiDoost** [comment]
In the name of God
Hi
Thank you for your answer

> The sentences must also be tokenized beforehand; otherwise you are computing character-level accuracy.

I don 't understand. May you give a real example?

thank you

**Comment by bdusell** [comment]
The arguments must be lists of sentences, and the sentences must be lists of words.

```python
summaries = [['I', 'am', 'a', 'teacher', '.']]
references = [['I', "'m", 'a', 'teacher', '.'], ['I', 'am', 'a', 'teacher', '.']]
result = rougescore.rouge_1(summaries, references, 0)
```

**Comment by MahdiDoost** [comment]
In the name of GOD
Hi,

Is followed code possible?

```
import rougescore

summaries =  ['I', "am", 'a', 'teacher', '.']

#  [['I', "'m", 'a', 'teacher', '.'], ['I', 'am', 'a', 'teacher', '.']] is ref1
              # ['I', "am", 'a', 'teacher', '.'] is ref2

references = [['I', "'m", 'a', 'teacher', '.'], ['I', 'am', 'a', 'teacher', '.']],['I', "am", 'a', 'teacher', '.']

result = rougescore.rouge_2(summaries, references, 0)

print(result)
```
thank you

**Comment by bdusell** [comment]
`summaries` should be a list of sentences (list of lists of strings):

```python
summaries =  [['I', "am", 'a', 'teacher', '.']]
```

Why does `ref1` have two sentences? `references` should also be a list of sentences.

**Comment by MahdiDoost** [comment]
In the name of God
Hi,

> summaries should be a list of sentences (list of lists of strings):

Result of bottom code is `0`.
```
import rougescore

# system summary & reference summary


#summaries =  ['I', 'am', 'a', 'teacher', '.']
summaries =  [['I', "am", 'a', 'teacher', '.']]
              

references = [['I', "'m", 'a', 'teacher', '.'], ['I', 'am', 'a', 'teacher', '.']]

# If you evaluate ROUGE by sentence list as above, set files=False
result = rougescore.rouge_2(summaries, references, 0)

print(result)
```
And result of bottom code is `0.75`.
```
import rougescore

# system summary & reference summary


#summaries =  ['I', 'am', 'a', 'teacher', '.']
summaries =  ['I', "am", 'a', 'teacher', '.']
              

references = [['I', "'m", 'a', 'teacher', '.'], ['I', 'am', 'a', 'teacher', '.']]

# If you evaluate ROUGE by sentence list as above, set files=False
result = rougescore.rouge_2(summaries, references, 0.5)

print(result)
```
Why is result 0, when summarize is list of lists of string? Is it logical?

> Why does ref1 have two sentences? references should also be a list of sentences.

Real mode references have several sentences. Have to be they merge?

Thank you

**Comment by bdusell** [comment]
Ah, my mistake, you're correct. Each function accepts only a single summary (via `peer`) and multiple references (via `models`). So your second snippet of code was correct.

```
import rougescore
summary =  ['I', "am", 'a', 'teacher', '.']
references = [['I', "'m", 'a', 'teacher', '.'], ['I', 'am', 'a', 'teacher', '.']]
result = rougescore.rouge_2(summary, references, 0.5)
print(result)
```

This is why it's good to document things. :)

**Comment by MahdiDoost** [comment]
In the name of God
Hi,
Please bring a Example for ref1 have 2 sentence and ref2 have 1 sentence and etc.
Thank you

**Comment by bdusell** [comment]
You can concatenate two sentences into one list.
```
import rougescore
summary = ['I', "am", 'a', 'teacher', '.']
references = [['I', "'m", 'a', 'teacher', '.', 'I', 'am', 'a', 'teacher', '.'], ['I', "am", 'a', 'teacher', '.']]
result = rougescore.rouge_2(summary, references, 0)
print(result)
```

**Comment by MahdiDoost** [comment]
In the Name of God
Hello,
Thank you very much for answer.
Good luck.
