### ISSUE TITLE
rougescore & persian

### ISSUE THREAD

**Issue by MahdiDoost** [bdusell/rougescore#3]
In the name of Allah
Hello,
Does rougescore support persian language?
Thank you

**Comment by bdusell** [comment]
It supports any language as long as the text is tokenized beforehand. This tokenizer looks like a good option for Persian: https://github.com/sobhe/hazm

Someone put together a list of some other options:
https://github.com/mhbashari/awesome-persian-nlp-ir#tokenization--segmentation

**Comment by MahdiDoost** [comment]
In the name of Allah
Hello,
Thank you for answer.
