### ISSUE TITLE
rougescore & folder

### ISSUE THREAD

**Issue by MahdiDoost** [bdusell/rougescore#4]
In the name of GOD.
Hello,
Peers and models are in folder. How does  rougescore work with folder.
Thank you

**Comment by bdusell** [comment]
Hi,

rougescore knows nothing about files and folders, it just works on individual sentences. How you deliver those sentences to the library is up to you. I made it this way on purpose, so that it would not be tied to any particular format.

**Comment by MahdiDoost** [comment]
In the name of Allah
Hello,
Thank you for answer.
